### ISSUE TITLE
Firing your last bullet does not work

### ISSUE THREAD

**Issue by Trainzack** [EmpiresCommunity/Unreal-Empires-Project#10]
When firing a weapon, the trigger pull that changes your ammo count from 1 to 0 results in a dry fire instead of a successful fire. If I recall correctly, this behavior changes depending on the network mode selected in the editor.

**Comment by RoyAwesome** [comment]
Fixed in B-56 and also I'm an idiot for this one.  The network behavior was relevant because of a non-predicted effect.
