### ISSUE TITLE
Vaulting while reloading causes issues

### ISSUE THREAD

**Issue by Trainzack** [EmpiresCommunity/Unreal-Empires-Project#12]
If you vault while you are reloading, this puts the gun into a state where you can't reload and you can't fire. Switching to another weapon and back resolves the issue, but sometimes you are unable to switch weapons.

Maybe the vault animation interrupts the reload animation, and because the reload animation never finishes you are stuck perpetually reloading? I think the correct behavior here would be for the vault to fully cancel the reload (or depending on how we want the game to feel, maybe we should let the players do both at once).

**Comment by RoyAwesome** [comment]
> Maybe the vault animation interrupts the reload animation, and because the reload animation never finishes you are stuck perpetually reloading

This is almost certainly the issue.  Reload should be blocked while vaulting

**Comment by RoyAwesome** [comment]
I also fixed this breaking Aim Down Sights, Firing, and Sprinting while I was in here.  It now cancels various abilities and blocks them from being reactivated until the vault is complete.
