### ISSUE TITLE
Dry firing follows weapon fire mode

### ISSUE THREAD

**Issue by Trainzack** [EmpiresCommunity/Unreal-Empires-Project#13]
If you dry fire an automatic weapon, the dry fire effect happens at the same rate as the automatic fire does when the weapon is loaded. This should be changed so that the dry fire effect happens only once, for the following reasons:

1. The player only needs one single audio cue to let them know that their weapon has no ammo.
2. Most real weapons depend on the energy from the cartridge firing to cycle the weapon and fire the next round. Without a bullet, the weapon will only make one sound.

We may want to consider having a different setup for weapons that have an electrical firing mechanism, like miniguns.

**Comment by RoyAwesome** [comment]
Fixed in B-55.  This required a bit more work to fix, but now all guns stop firing when they try to emit a shot and there is no ammo remaining.
