### ISSUE TITLE
1P weapon view models sometimes disappear.

### ISSUE THREAD

**Issue by Trainzack** [EmpiresCommunity/Unreal-Empires-Project#14]
At some view angles, at some points in the idle animation, for some weapons, while zoomed, the entire weapon will disappear as if the game thinks it shouldn't be rendered.
![image](https://github.com/EmpiresCommunity/Unreal-Empires-Project/assets/19575360/4a5dd4ce-c98e-4d94-b278-5c4d4f5f98cd)

**Comment by Trainzack** [comment]
Oops, the attached image doesn't actually demonstrate the issue. Here's after I moved around slightly:

![image](https://github.com/EmpiresCommunity/Unreal-Empires-Project/assets/19575360/39bd658d-705f-4fb1-b675-61133ba44b2e)

**Comment by RoyAwesome** [comment]
There should be a checkbox in the mesh component to deal with this.

**Comment by RoyAwesome** [comment]
I checked "Use Attach Parent Bounds" which should fix this.  Build 51 should have the fix.

**Comment by RoyAwesome** [comment]
also @Trainzack i was never able to reproduce this bug, can you see if it's still happening after build 51?

**Comment by Trainzack** [comment]
@RoyAwesome I can no longer reproduce this, it seems to be fixed now.
