### ISSUE TITLE
Scenario Baen Island Conquest causing Fatal Error

### ISSUE THREAD

**Issue by Neoony** [EmpiresCommunity/Unreal-Empires-Project#2]
When trying to start Baen Island Conquest as host from the Steam Empires Project
Listen server was checked/enabled

![image](https://github.com/EmpiresCommunity/Unreal-Empires-Project/assets/24975075/1f6f867a-7fff-41ae-9053-147471022788)

[UECC-Windows-6E0F8ED445F889AF34D3F9B4E8EE3E87_0000.zip](https://github.com/EmpiresCommunity/Unreal-Empires-Project/files/11851588/UECC-Windows-6E0F8ED445F889AF34D3F9B4E8EE3E87_0000.zip)

there was one empires.log inside the crash folder
And one in F:\Games\SteamLibrary\steamapps\common\projectEmpires\Empires\Saved\Logs
I renamed the one from the crash folder to empires-crash.log

In the empires-crash.log
this seems interesting (last line):
[2023.06.23-19.21.28:130][288]LogStreaming: Warning: LoadPackage: SkipPackage: /BaenIsland/Terrain/L_BaenIsland_Imported (0xF174EBC6DF598777) - The package to load does not exist on disk or in the loader

**Comment by RoyAwesome** [comment]
> SkipPackage: /BaenIsland/Terrain/L_BaenIsland_Imported (0xF174EBC6DF598777) - The package to load does not exist on disk or in the loader

Implies this isn't getting cooked, but that's odd because it's showing up in the list (and thus exists on disk).  Will investigate further

**Comment by RoyAwesome** [comment]
Crash is fixed in build 48.  Working on fixing the fact that the map isn't being cooked.

**Comment by RoyAwesome** [comment]
Baen Island now cooks
